# Generated by Django 5.0.2 on 2024-02-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr_name', models.CharField(max_length=200)),
                ('pr_name_en', models.CharField(max_length=200)),
            ],
        ),
    ]
